CREATE TABLE T1 (
    id INT PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE T2 (
    title CHAR(32) PRIMARY KEY,
    t1_id INT NOT NULL,
    FOREIGN KEY (t1_id) REFERENCES T1(id) ON DELETE CASCADE
);

ALTER TABLE T1
ADD t2_title CHAR(32) NOT NULL;
ALTER TABLE T1
ADD FOREIGN KEY (t2_title) REFERENCES T2(title) ON DELETE CASCADE;
