CREATE DATABASE OnDeleteDemo;
CONNECT OnDeleteDemo;

CREATE TABLE ParentA (
    id INTEGER PRIMARY KEY DEFAULT 0
);
CREATE TABLE ChildA (
    id INTEGER PRIMARY KEY,
    a_id INTEGER DEFAULT 1,
    /* FOREIGN KEY (a_id) REFERENCES ParentA(id) ON DELETE SET NULL */
    FOREIGN KEY (a_id) REFERENCES ParentA(id) ON DELETE SET DEFAULT
    /* FOREIGN KEY (a_id) REFERENCES ParentA(id) ON DELETE CASCADE */
);

INSERT INTO ParentA VALUES (0);
INSERT INTO ParentA VALUES (1);
INSERT INTO ParentA VALUES (2);
INSERT INTO ParentA VALUES (3);

INSERT INTO ChildA VALUES (1, 1);
INSERT INTO ChildA VALUES (2, 1);
INSERT INTO ChildA VALUES (3, 2);
INSERT INTO ChildA VALUES (4, 3);

SELECT * FROM ChildA;
DELETE FROM ParentA WHERE id = 2;
SELECT * FROM ChildA;

DROP TABLE ChildA;
DROP TABLE ParentA;
DROP DATABASE OnDeleteDemo;
